"""
Curated IQ test question bank — 30 questions across 5 categories.
Answers are only stored server-side; clients never receive them.
"""

QUESTION_BANK = [
    # ── LOGICAL REASONING ──────────────────────────────────────────────
    {
        "id": "L1",
        "category": "Logical Reasoning",
        "text": "All Bloops are Razzies. All Razzies are Lazzies. Therefore, all Bloops are Lazzies.",
        "options": {"A": "True", "B": "False", "C": "Cannot determine", "D": "Only sometimes true"},
        "correct": "A",
        "difficulty": 1,
    },
    {
        "id": "L2",
        "category": "Logical Reasoning",
        "text": "A man is looking at a photograph. He says: 'Brothers and sisters I have none, but this man's father is my father's son.' Who is in the photograph?",
        "options": {"A": "His father", "B": "Himself", "C": "His son", "D": "His brother"},
        "correct": "C",
        "difficulty": 3,
    },
    {
        "id": "L3",
        "category": "Logical Reasoning",
        "text": "Some cats are dogs. Some dogs are mice. Which conclusion is definitely true?",
        "options": {
            "A": "Some cats are mice",
            "B": "Some mice are cats",
            "C": "No definite conclusion",
            "D": "All cats are mice",
        },
        "correct": "C",
        "difficulty": 2,
    },
    {
        "id": "L4",
        "category": "Logical Reasoning",
        "text": "If 'FRIEND' is coded as 'HUMJTK', how is 'CANDLE' coded?",
        "options": {"A": "EDRIRL", "B": "DCQHQJ", "C": "EDRJMH", "D": "EDRJMK"},
        "correct": "A",  # each letter +2
        "difficulty": 3,
    },
    {
        "id": "L5",
        "category": "Logical Reasoning",
        "text": "Pointing to a man, a woman says, 'His mother is the only daughter of my mother.' How is the woman related to the man?",
        "options": {"A": "Grandmother", "B": "Mother", "C": "Sister", "D": "Aunt"},
        "correct": "B",
        "difficulty": 2,
    },
    {
        "id": "L6",
        "category": "Logical Reasoning",
        "text": "In a row of 40 students, Ravi is 11th from the left. What is his position from the right?",
        "options": {"A": "28th", "B": "29th", "C": "30th", "D": "31st"},
        "correct": "C",
        "difficulty": 1,
    },

    # ── NUMERICAL / PATTERN ────────────────────────────────────────────
    {
        "id": "N1",
        "category": "Numerical Reasoning",
        "text": "What comes next in the series: 2, 6, 12, 20, 30, __?",
        "options": {"A": "40", "B": "42", "C": "44", "D": "46"},
        "correct": "B",
        "difficulty": 2,
    },
    {
        "id": "N2",
        "category": "Numerical Reasoning",
        "text": "What comes next: 1, 1, 2, 3, 5, 8, 13, __?",
        "options": {"A": "18", "B": "20", "C": "21", "D": "22"},
        "correct": "C",
        "difficulty": 1,
    },
    {
        "id": "N3",
        "category": "Numerical Reasoning",
        "text": "A clock shows 3:15. What is the angle between the hour and minute hands?",
        "options": {"A": "0°", "B": "7.5°", "C": "15°", "D": "22.5°"},
        "correct": "B",
        "difficulty": 3,
    },
    {
        "id": "N4",
        "category": "Numerical Reasoning",
        "text": "If 5 machines make 5 widgets in 5 minutes, how long does it take 100 machines to make 100 widgets?",
        "options": {"A": "5 minutes", "B": "10 minutes", "C": "100 minutes", "D": "1 minute"},
        "correct": "A",
        "difficulty": 3,
    },
    {
        "id": "N5",
        "category": "Numerical Reasoning",
        "text": "What is 15% of 80% of 500?",
        "options": {"A": "48", "B": "60", "C": "75", "D": "90"},
        "correct": "B",
        "difficulty": 2,
    },
    {
        "id": "N6",
        "category": "Numerical Reasoning",
        "text": "The average of 5 numbers is 20. A sixth number is added, making the average 25. What is the sixth number?",
        "options": {"A": "45", "B": "50", "C": "55", "D": "60"},
        "correct": "B",
        "difficulty": 2,
    },
    {
        "id": "N7",
        "category": "Numerical Reasoning",
        "text": "What comes next: 144, 121, 100, 81, 64, __?",
        "options": {"A": "36", "B": "49", "C": "25", "D": "16"},
        "correct": "B",
        "difficulty": 1,
    },

    # ── SPATIAL / VISUAL ───────────────────────────────────────────────
    {
        "id": "S1",
        "category": "Spatial Reasoning",
        "text": "A cube has 6 faces, 8 vertices. How many edges does it have?",
        "options": {"A": "10", "B": "12", "C": "14", "D": "16"},
        "correct": "B",
        "difficulty": 1,
    },
    {
        "id": "S2",
        "category": "Spatial Reasoning",
        "text": "How many squares (of all sizes) are in a standard 4×4 grid?",
        "options": {"A": "16", "B": "20", "C": "30", "D": "36"},
        "correct": "C",
        "difficulty": 3,
    },
    {
        "id": "S3",
        "category": "Spatial Reasoning",
        "text": "If you fold a square piece of paper in half twice and cut a circle in the centre, how many holes will you have when unfolded?",
        "options": {"A": "1", "B": "2", "C": "4", "D": "8"},
        "correct": "C",
        "difficulty": 2,
    },
    {
        "id": "S4",
        "category": "Spatial Reasoning",
        "text": "A snail is at the bottom of a 10-metre well. Each day it climbs 3 metres and each night it slides back 2 metres. On which day does it reach the top?",
        "options": {"A": "8th day", "B": "9th day", "C": "10th day", "D": "7th day"},
        "correct": "A",
        "difficulty": 2,
    },

    # ── VERBAL / ANALOGIES ─────────────────────────────────────────────
    {
        "id": "V1",
        "category": "Verbal Ability",
        "text": "Oar is to Boat as Pedal is to __?",
        "options": {"A": "Wheel", "B": "Bicycle", "C": "Road", "D": "Engine"},
        "correct": "B",
        "difficulty": 1,
    },
    {
        "id": "V2",
        "category": "Verbal Ability",
        "text": "Which word does NOT belong? Hammer, Nail, Wrench, Screwdriver",
        "options": {"A": "Hammer", "B": "Nail", "C": "Wrench", "D": "Screwdriver"},
        "correct": "B",
        "difficulty": 1,
    },
    {
        "id": "V3",
        "category": "Verbal Ability",
        "text": "Rearrange the letters 'CIFAIPC' to make a word. What is it?",
        "options": {"A": "PACIFIC", "B": "PACIFIC", "C": "PACIFIC", "D": "PACIFIC"},
        "correct": "A",
        "difficulty": 1,
    },
    {
        "id": "V4",
        "category": "Verbal Ability",
        "text": "DOCTOR : HOSPITAL :: JUDGE : ?",
        "options": {"A": "Lawyer", "B": "Jury", "C": "Court", "D": "Law"},
        "correct": "C",
        "difficulty": 1,
    },
    {
        "id": "V5",
        "category": "Verbal Ability",
        "text": "Which word is most similar in meaning to 'EPHEMERAL'?",
        "options": {"A": "Eternal", "B": "Transient", "C": "Ancient", "D": "Solid"},
        "correct": "B",
        "difficulty": 2,
    },
    {
        "id": "V6",
        "category": "Verbal Ability",
        "text": "Which word is the odd one out? Mars, Neptune, Moon, Saturn, Jupiter",
        "options": {"A": "Mars", "B": "Neptune", "C": "Moon", "D": "Saturn"},
        "correct": "C",
        "difficulty": 1,
    },

    # ── WORKING MEMORY / PROCESSING ────────────────────────────────────
    {
        "id": "M1",
        "category": "Working Memory",
        "text": "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?",
        "options": {"A": "$0.10", "B": "$0.05", "C": "$0.15", "D": "$0.20"},
        "correct": "B",
        "difficulty": 3,
    },
    {
        "id": "M2",
        "category": "Working Memory",
        "text": "In a lake, a patch of lily pads doubles every day. If the lake is fully covered on day 48, when was it half covered?",
        "options": {"A": "Day 24", "B": "Day 36", "C": "Day 44", "D": "Day 47"},
        "correct": "D",
        "difficulty": 3,
    },
    {
        "id": "M3",
        "category": "Working Memory",
        "text": "Lara has twice as many brothers as sisters. Each of her brothers also has twice as many brothers as sisters. How many boys and girls are in the family?",
        "options": {"A": "4 boys, 3 girls", "B": "4 boys, 2 girls", "C": "3 boys, 2 girls", "D": "5 boys, 3 girls"},
        "correct": "A",
        "difficulty": 3,
    },
    {
        "id": "M4",
        "category": "Working Memory",
        "text": "How many times does the digit '1' appear when you write all numbers from 1 to 100?",
        "options": {"A": "11", "B": "20", "C": "21", "D": "19"},
        "correct": "C",
        "difficulty": 3,
    },
    {
        "id": "M5",
        "category": "Working Memory",
        "text": "Three friends share a room. The room costs $30, so each pays $10. Later the manager refunds $5. The bellboy keeps $2 and returns $1 each. Now each has paid $9 (total $27) + bellboy's $2 = $29. Where is the missing dollar?",
        "options": {
            "A": "The manager has it",
            "B": "There is no missing dollar — the maths is flawed",
            "C": "The bellboy has it",
            "D": "It never existed",
        },
        "correct": "B",
        "difficulty": 3,
    },
    {
        "id": "M6",
        "category": "Working Memory",
        "text": "You have a 3-litre jug and a 5-litre jug. How do you measure exactly 4 litres?",
        "options": {
            "A": "Fill 5L, pour into 3L, empty 3L, pour remainder into 3L, fill 5L again, fill up the 3L — left with 4L in 5L jug",
            "B": "Fill 3L twice and add to 5L jug",
            "C": "Impossible",
            "D": "Fill 5L, pour 1L out",
        },
        "correct": "A",
        "difficulty": 2,
    },
    {
        "id": "M7",
        "category": "Working Memory",
        "text": "What is the next number? 3, 7, 13, 21, 31, 43, __?",
        "options": {"A": "55", "B": "57", "C": "59", "D": "61"},
        "correct": "B",
        "difficulty": 2,
    },
]
